version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    image: news_task
    container_name: news_task
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    expose:
      - "9000"
    networks:
      - app_net

  nginx:
    image: nginx:alpine
    container_name: news_task_nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "9090:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
